### ISSUE TITLE
Error: your purchase was successful, but we were not able to send you an email.

### ISSUE THREAD

**Issue by prasannasm87** [ParsePlatform/ParseStore#15]
I have created an account in @mailgun, and gave api-key and public key in main.js. Then I deploy successfully. Still I am getting this error. Please give any suggestion.

Error : Your purchase was successful, but we were not able to send you an email. Contact us at store@parse.com if you have any questions.

**Comment by gfosco** [comment]
Sounds like Mailgun returned an error.  Add a line in your cloud code where this error is generated to log out the 'error' object.
